name: Continuous Delivery

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  CD-Go:
    uses: aleogr/pipeline/.github/workflows/cd-go.yml@v1
    with:
        workdir: goapp
